on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: asdf-vm/actions/install@v3
      - uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59
      - run: go build -v ./...
      - run: go test -v ./...
