on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: asdf-vm/actions/install@v3

      - uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59

      - run: go build -v ./...
      - run: go test -v -covermode atomic -coverprofile=cover

      - if: github.ref == 'refs/heads/main'
        env:
          COVERALLS_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          go install github.com/mattn/goveralls@latest
          asdf reshim golang
          goveralls -coverprofile=cover -service=github
